### ISSUE TITLE
Are the input of MRE incomplete?

### ISSUE THREAD

**Issue by JihaoLee** [zztianzz/PF-Net-Point-Fractal-Network#13]
Thank you for your open source code. Could you answer a question to me? 
I notice that there are 3 scales for the input of MRE. For one model in ShapeNet Parts, the number of points is 2048. However, one of your scale is 2048. This is complete point cloud. You utilize complete point cloud models to accomplish completion task. How to explain this or how do I understand it? Thanks again!

**Comment by zztianzz** [comment]
In fact, the '2048' scales contain partial point cloud with numbers of [0,0,0] points.   The model can fit any numbers of input points after training. At first, We want to translate those [0,0,0] points to generate the missing regions. But we have tested that those [0,0,0] points have no effect to the final results, so you can ignore them or just use this code. Thanks.

**Comment by JihaoLee** [comment]
Thank you very much!
And, you select 5 viewpoint. [1, 0, 1], [-1, 0, 0]...... What do these coordinates mean?

**Comment by zztianzz** [comment]
Those points are the center of the missing regions. You can change the missing strategy yourself by modifing this part.(for example missing half of the point cloud)
