### ISSUE TITLE
show_FPNet.py 跑不通

### ISSUE THREAD

**Issue by fugn690621** [zztianzz/PF-Net-Point-Fractal-Network#2]
第27行的引用
`from model_recon_3layers_robustness import _netlocalD,_netG`
没有来源，报错为
`ModuleNotFoundError: No module named 'model_recon_3layers_robustness'`
麻烦解决一下

**Comment by zztianzz** [comment]
I will update the code in the next few days.

**Comment by zztianzz** [comment]
Please add a file named "Checkpoint" before training and use show_recon.py to generate final txt files.Then you can use Meshlab to visualize the point cloud.
