### ISSUE TITLE
download dataset, there is no json file

### ISSUE THREAD

**Issue by AngZhai** [zztianzz/PF-Net-Point-Fractal-Network#20]
step1, in the .sh file which to download dataset:

mv shapenet_part_overallid_to_catid_partid.json shapenet_part/shapenetcore_partanno_segmentation_benchmark_v0/

there is no such file ' shapenet_part_overallid_to_catid_partid.json'. how to get this file.

**Comment by comewei** [comment]
hello, do you find it .
