### ISSUE TITLE
About Chamfer Distance.

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [zztianzz/PF-Net-Point-Fractal-Network#7]
I trained a model only with catagorty 'Car' and test Chamfer Distance with your code 'show_CD'.
It reported an average CD: 0.003873.
Is that right? Because I think it is an unreasonble result. Some state-of-the-art work(e.g. PCN, Top-Net) report its 3D completion task CD around 0.0008.
I didn't see any quantitative results in your paper so I asked here.
Looking for your reply :)

**Comment by SkyeFromKindergarten** [comment]
Sorry, but I don't know why you don't answer the question and just close it?

**Comment by zztianzz** [comment]
i have answer your questions by senting you an email on 4.6

**Comment by zztianzz** [comment]
My github link to my mobile phone email app. I use it to sent you  emails directly many times. Have you received them?

**Comment by SkyeFromKindergarten** [comment]
Sorry, I don't recive any of them.

**Comment by SkyeFromKindergarten** [comment]
Maybe you could forward those emails to guoyan8833@163.com if convenient.
Thanks ~

**Comment by zztianzz** [comment]
Since this question is not about the code but about the paper. I have sent you an emails to explain my ideas of your questions.

**Comment by zztianzz** [comment]
It looks like many of my answers lost lolllll

**Comment by zztianzz** [comment]
I find that you lost 3-4 emails.

**Comment by SkyeFromKindergarten** [comment]
I have recived your emails! Thank you!

**Comment by Katrina-cmd** [comment]
@SkyeFromKindergarten 
Hello, I also encountered the same problem. How did you understand this problem in the end?
